sudo: required

matrix:
  include:

    - language: scala
      scala:
        - 2.11.11
      script:
        - sbt clean coverage test coverageReport &&
          sbt coverageAggregate
      after_success:
        - sbt coveralls
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python: 2.7
      install: sudo pip install -r docs/requirements.txt
      script: make -C docs/ html
