sudo: required
language: scala
scala:
  - 2.11.11

before_install:
- sudo apt install python python-pip python-setuptools
install:
- sudo pip install -r requirements.txt
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
  - make html
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)