sudo: required
matrix:
  - env:
      TEST_COMMAND_1: "sbt clean coverage test coverageReport"
      TEST_COMMAND_2: "sbt coverageAggregate"

  - env:
      TEST_COMMAND_1: "make -C docs html"
      TEST_COMMAND_2: "echo documentation build"


before_install:
- sudo apt install python python-pip python-setuptools
install:
- sudo pip install -r requirements.txt
script:
  - $TEST_COMMAND_1
  - $TEST_COMMAND_2
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
