sudo: required
language: scala
scala:
  - 2.11.11
matrix:
  include:
    - language: scala
      scala:
        - 2.11.11
      env:
        TEST_SCRIPT: "tests/tool_test.sh"
    - language: python
      python: 2.7
      env:
        TEST_SCRIPT: "tests/documentation_test.sh"
script:
  - bash "$TEST_SCRIPT"
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
