sudo: required
language: scala
scala:
  - 2.11.11
matrix:
  include:
    - env:
        TEST_SCRIPT: "tests/tool_test.sh"
    - env:
        TEST_SCRIPT: "tests/documentation_test.sh"

script:
  - bash -c "$TEST_SCRIPT"
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
